export const REQUEST_MENU_PENDING = 'REQUEST_MENU_PENDING';
export const REQUEST_MENU_SUCCESS = 'REQUEST_MENU_SUCCESS';
export const REQUEST_MENU_FAIL = 'REQUEST_MENU_FAIL';

export const MAKE_ORDER_REQUEST = 'MAKE_ORDER_REQUEST';
export const MAKE_ORDER_SUCCESS = 'MAKE_ORDER_SUCCESS';
export const MAKE_ORDER_FAIL = 'MAKE_ORDER_FAIL';

export const UPDATE_SALES_FILTER = 'UPDATE_SALES_FILTER';

export const REQUEST_SALES_PENDING = 'REQUEST_SALES_PENDING';
export const REQUEST_SALES_SUCCESS = 'REQUEST_SALES_SUCCESS';
export const REQUEST_SALES_FAIL = 'REQUEST_SALES_FAIL';
